describe('Profile Management & Validation', () => {
    let testEmail = `profileQA_${Date.now()}@example.com`;
    let password = 'Tester123!';

    it('01 Setup: Register test user', () => {
        cy.log('Registering a new user');
        cy.visit('/register');
        cy.get('input[name="fullName"]').type('QA Profile Tester');
        cy.get('input[name="email"]').type(testEmail);
        cy.get('input[name="password"]').type(password);
        cy.screenshot('01-profile-register-filled');
        cy.get('button[type="submit"]').click();
        cy.url().should('include', '/login');
    });

    it('02 Authentication Check: Unauthorized access blocked', () => {
        cy.log('Attempting to access profile without logging in');
        cy.visit('/profile/edit');
        cy.url().should('include', '/login');
        cy.screenshot('02-profile-unauthorized-redirect');
    });

    it('03 Valid Update Flow and UI Check', () => {
        cy.log('Logging in');
        cy.visit('/login');
        cy.get('input[name="email"]').type(testEmail);
        cy.get('input[name="password"]').type(password);
        cy.get('button[type="submit"]').click();

        cy.log('Navigating to Edit Profile');
        cy.visit('/profile/edit');
        cy.contains('Update Your Profile').should('be.visible');
        cy.screenshot('03-profile-edit-ui');

        cy.log('Filling out the form');
        cy.get('input[name="location"]').type('QA City, TestCountry');
        cy.get('input[name="university"]').type('QA Testing University');
        cy.get('textarea[name="bio"]').type('This is a test bio generated by Cypress QA.');
        cy.get('input[name="phoneNumber"]').type('+1234567890');

        cy.log('Uploading profile picture');
        cy.get('input[type="file"]').selectFile('cypress/fixtures/test.jpg');
        cy.screenshot('04-profile-edit-filled');

        cy.log('Submitting profile update');
        cy.get('button[type="submit"]').contains('Save Profile').click();

        cy.log('Verifying updated profile information');
        cy.url().should('include', '/profile');
        cy.contains('Profile updated successfully').should('be.visible');
        cy.contains('QA City, TestCountry').should('be.visible');
        cy.contains('QA Testing University').should('be.visible');
        cy.screenshot('05-profile-view-updated');

        cy.log('Toggling Availability');
        cy.get('form[action="/profile/availability/toggle"] button').click();
        cy.contains('Availability status updated').should('be.visible');
        cy.screenshot('06-profile-availability-toggled');
    });

    it('04 Validation and Error Handling', () => {
        cy.log('Logging in');
        cy.visit('/login');
        cy.get('input[name="email"]').type(testEmail);
        cy.get('input[name="password"]').type(password);
        cy.get('button[type="submit"]').click();

        cy.visit('/profile/edit');

        cy.log('Clearing required fields for validation error');
        cy.get('input[name="fullName"]').clear();
        cy.screenshot('07-profile-edit-invalid-input');

        cy.log('Submitting invalid form');
        cy.get('button[type="submit"]').contains('Save Profile').click();

        cy.log('Verifying error messages');
        cy.get('.error-message').should('exist');
        cy.screenshot('08-profile-edit-validation-error');
    });
});
